app/urls.py
from django.urls import path
from app.views import (
    Index,
    UserProfile,
    UserProfileUpdate,
    AccountList,
    AccountTransfer,
    BankList,
    BankCreate,
    BankDetail,
    BankUpdate,
    BankDelete,
    CardList,
    CardCreate,
    CardDetail,
    CardUpdate,
    CardDelete,
    SendSearchUser,
    SendMoney,
    SendSuccess,
    RequestSearchUser,
    RequestMoney,
    RequestSuccess,
    ActivityList,
    IncompleteTranList,
    IncompletePayment,
    IncompletePaymentConfirm,
    PaymentComplete,
    IncompleteRequest,
    IncompleteRequestDelete,
    StaffTransactionList,
    StaffTranDetail,
    StaffTranDelete,
    StaffUserList,
    StaffUserInfo,
    StaffUserTran,
    StaffUserTranDetail,
    StaffUserTranDelete,
    StaffUserPayment,
    StaffUserBankDetail,
    StaffUserCardDetail,
)

urlpatterns = [
    path('index/', Index.as_view(), name='index'),
    path('profile/', UserProfile.as_view(), name='profile'),
    path('profile/edit/', UserProfileUpdate.as_view(), name='profile_update'),
    path('wallet/', AccountList.as_view(), name='account'),
    path('transfer/<int:pk>/', AccountTransfer.as_view(), name='account_transfer'),
    path('bank/', BankList.as_view(), name='bank'),
    path('bank/add/', BankCreate.as_view(), name='bank_create'),
    path('bank/<int:pk>/detail/', BankDetail.as_view(), name='bank_detail'),
    path('bank/<int:pk>/update/', BankUpdate.as_view(), name='bank_update'),
    path('bank/<int:pk>/delete/', BankDelete.as_view(), name='bank_delete'),
    path('card/', CardList.as_view(), name='card'),
    path('card/add/', CardCreate.as_view(), name='card_create'),
    path('card/<int:pk>/detail/', CardDetail.as_view(), name='card_detail'),
    path('card/<int:pk>/update/', CardUpdate.as_view(), name='card_update'),
    path('card/<int:pk>/delete/', CardDelete.as_view(), name='card_delete'),
    path('activity/', ActivityList.as_view(), name='activity'),
    path('send/', SendSearchUser.as_view(), name='send'),
    path('send/<int:pk>/', SendMoney.as_view(), name='send_money'),
    path('send/success/', SendSuccess.as_view(), name='send_success'),
    path('request/', RequestSearchUser.as_view(), name='request'),
    path('request/<int:pk>/', RequestMoney.as_view(), name='request_money'),
    path('request/success/', RequestSuccess.as_view(), name='request_success'),
    path('incomplete/', IncompleteTranList.as_view(), name='incomplete'),
    path('incomplete/payment/<int:pk>/detail/', IncompletePayment.as_view(), name='incomplete_payment'),
    path('incomplete/payment/<int:pk>/confirm/', IncompletePaymentConfirm.as_view(), name='incomplete_payment_confirm'),
    path('incomplete/payment/complete/', PaymentComplete.as_view(), name='payment_complete'),
    path('incomplete/request/<int:pk>/detail/', IncompleteRequest.as_view(), name='incomplete_request'),
    path('incomplete/request/<int:pk>/delete/', IncompleteRequestDelete.as_view(), name='incomplete_request_delete'),

    path('staff/transaction/', StaffTransactionList.as_view(), name='staff_transaction'),
    path('staff/transaction/<int:pk>/detail/', StaffTranDetail.as_view(), name='staff_tran_detail'),
    path('staff/transaction/<int:pk>/delete/', StaffTranDelete.as_view(), name='staff_tran_delete'),
    path('staff/user/', StaffUserList.as_view(), name='staff_user'),
    path('staff/user/<int:pk>/info/', StaffUserInfo.as_view(), name='staff_user_info'),
    path('staff/user/<int:pk>/payment/', StaffUserPayment.as_view(), name='staff_user_pay'),
    path('staff/user/<int:pk>/bank/<int:bpk>', StaffUserBankDetail.as_view(), name='staff_user_bank'),
    path('staff/user/<int:pk>/card/<int:cpk>/', StaffUserCardDetail.as_view(), name='staff_user_card'),
    path('staff/user/<int:pk>/transactions/', StaffUserTran.as_view(), name='staff_user_tran'),
    path('staff/user/<int:pk>/transactions/<int:tpk>/detail', StaffUserTranDetail.as_view(), name='staff_user_tran_detail'),
    path('staff/user/<int:pk>/transactions/<int:tpk>/delete', StaffUserTranDelete.as_view(), name='staff_user_tran_delete'),

]

chiang_pinhuey_final_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

from app.views import (
    UserLogin,
    UserLogout,
    UserRegistration,
    UserResetPwd,
)

urlpatterns = [
    path('',
         RedirectView.as_view(
             pattern_name='index',
             permanent=False
         )),

    path('admin/', admin.site.urls),

    path('login/', UserLogin.as_view(template_name='app/login.html'), name='user_login'),
    path('logout/', UserLogout.as_view(), name='user_logout'),
    path('registration/', UserRegistration.as_view(), name='registration'),
    path('reset-password/', UserResetPwd.as_view(), name='reset_password'),

    path('', include('app.urls'))



] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User, AbstractUser
from django.urls import reverse


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birthday = models.DateField(default=None)
    address = models.CharField(max_length=255, default=None)

    def __str__(self):
        return self.user.username


class PaymentMethod(models.Model):
    method_id = models.AutoField(primary_key=True)
    method_type = models.CharField(max_length=255, default='')
    user = models.ForeignKey(User, related_name='payment_user', on_delete=models.PROTECT)

    def __str__(self):
        return str(self.method_id)


class Account(models.Model):
    payment = models.OneToOneField(PaymentMethod, on_delete=models.CASCADE)
    balance = models.FloatField(default=0.00)

    def __str__(self):
        return 'Account: %s' % self.payment.user.username

    def get_update_url(self):
        return reverse('account_transfer', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        # ensure that the database only stores 2 decimal places
        self.balance = round(self.balance, 2)
        super(Account, self).save(*args, **kwargs)


class Bank(models.Model):
    payment = models.OneToOneField(PaymentMethod, on_delete=models.CASCADE)
    owner_first_name = models.CharField(max_length=255, default=None)
    owner_last_name = models.CharField(max_length=255, default=None)
    routing_number = models.CharField(max_length=9, default=None)
    account_number = models.CharField(max_length=10, default=None)

    def __str__(self):
        return 'Bank: ****%s' % self.account_number[5:]

    def get_absolute_url(self):
        return reverse('bank_detail', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('bank_update', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('bank_delete', kwargs={'pk': self.pk})

    class Meta:
        unique_together = ('routing_number', 'account_number')


Card_Type = (
    ('Credit', 'Credit Card'),
    ('Debit', 'Debit Card'),
)


class Card(models.Model):
    payment = models.OneToOneField(PaymentMethod, on_delete=models.DO_NOTHING)
    card_type = models.CharField(max_length=45, choices=Card_Type)
    card_number = models.CharField(max_length=16, default=None)
    owner_first_name = models.CharField(max_length=45)
    owner_last_name = models.CharField(max_length=45)
    security_code = models.CharField(max_length=3, default=None)
    expiration_date = models.DateField(default=None)

    def get_absolute_url(self):
        return reverse('card_detail', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('card_update', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('card_delete', kwargs={'pk': self.pk})

    def __str__(self):
        return '%s Card: ************%s' % (self.card_type, self.card_number[12:])

    class Meta:
        unique_together = ('card_type', 'owner_first_name', 'owner_last_name',
                           'card_number', 'security_code', 'expiration_date')
        ordering = ['card_type', 'card_number']


Transaction_Type = (
    ('send', 'Send'),
    ('request', 'Request'),
    ('transfer', 'Transfer'),
)


Categories = (
    ('Bank', 'Bank Transfer'),
    ('Utilities', 'Bills & Utilities'),
    ('Transportation', 'Auto & Transport'),
    ('Groceries', 'Groceries'),
    ('Food', 'Food'),
    ('Shopping', 'Shopping'),
    ('Health', 'Healthcare'),
    ('Education', 'Education'),
    ('Travel', 'Travel'),
    ('Housing', 'Housing'),
    ('Entertainment', 'Entertainment'),
    ('Others', 'Others'),
)


class Transaction(models.Model):
    transaction_id = models.AutoField(primary_key=True)
    transaction_type = models.CharField(max_length=45, choices=Transaction_Type, default='')
    category = models.CharField(max_length=45, choices=Categories)
    amount = models.FloatField(default=0.00)
    description = models.CharField(max_length=200, default=False)
    create_date = models.DateTimeField(default=now, editable=False)
    is_complete = models.BooleanField(default=False)
    receiver = models.ForeignKey(User, related_name='receiver', on_delete=models.PROTECT, default='')
    creator = models.ForeignKey(User, related_name='creator', on_delete=models.PROTECT, default='')
    payment_method = models.ForeignKey(PaymentMethod, related_name='payment_method',
                                       on_delete=models.PROTECT, default='', null=True)

    def get_absolute_url(self):
        return reverse('staff_tran_detail', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('staff_tran_delete', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        # ensure that the database only stores 2 decimal places
        self.amount = round(self.amount, 2)
        super(Transaction, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.transaction_id)

    class Meta:
        ordering = ['category']

app/templates/index.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Easy Pay</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <!--<link rel="shortcut icon" type="image/x-icon" href="../static/img/favicon.png"> -->
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/slicknav.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">


    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-xl-3 col-lg-2">
                            <div class="logo">
                                <a href="{% url 'index' %}">
                                    <img src="{% static 'img/logo.png' %}" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-7">
                            <div class="main-menu  d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a class="active" href="{% url 'index' %}">Home</a></li>
                                        {% if perms.app.add_transaction%}
                                            <li><a href="{% url 'activity' %}">Activity</a></li>
                                        {% endif %}
                                        {% if perms.app.add_transaction %}
                                            <li><a href="{% url 'send' %}">Send & Request</a>
                                        {% endif %}
                                        {% if perms.app.add_account%}
                                            <li><a href="{% url 'account' %}">Wallet</a></li>
                                        {% endif %}
                                        {% if perms.app.change_profile %}
                                            <li><a href="{% url 'profile' %}">User Profile</a></li>
                                        {% endif %}

                                        {% if perms.app.delete_transaction %}
                                            <li><a href="{% url 'staff_user' %}">User List</a></li>
                                        {% endif %}
                                        {% if perms.app.delete_transaction %}
                                            <li><a href="{% url 'staff_transaction' %}">Transactions</a></li>
                                        {% endif %}

                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                            <div class="Appointment">
                                <div>
                                    {% if user.is_authenticated %}
                                        <div class="book_btn d-none d-lg-block"><a href="{% url 'user_logout' %}">Log Out</a></div>
                                    {% else %}
                                        <div class="book_btn d-none d-lg-block"><a href="{% url 'user_login' %}">Login</a></div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->

    <!-- slider_area_start -->
    <div class="slider_area">
        <div class="slider_active owl-carousel">
            <div class="single_slider  d-flex align-items-center slider_bg_1">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="slider_text ">
                                <h3> <span>Easy Pay</span> </h3>
                                <p>With easy pay, you can not only send and transfer money <br> within a second, but also
                                    track your spendings in few steps.</p>
                                {% if perms.app.add_account %}
                                    <a href="{% url 'account' %}" class="boxed-btn3">Check Wallet</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- slider_area_end -->

    <!-- service_area_start -->
    <div class="service_area">
        <div class="container p-0">
            <div class="row no-gutters">
                <div class="col-xl-4 col-md-4">
                    <div class="single_service">
                        <div class="icon">
                            <i class="flaticon-money"></i>
                        </div>
                        <h3>Send</h3>
                        <p>Send your money to your friend within a minute.</p>
                        {% if perms.app.add_transaction %}
                            <a href="{% url 'send' %}" class="boxed-btn3-white">Send</a>
                        {% else %}
                            <br>
                        {% endif %}
                    </div>
                </div>
                <div class="col-xl-4 col-md-4">
                    <div class="single_service">
                        <div class="icon">
                            <i class="flaticon-money-2"></i>
                        </div>
                        <h3>Request</h3>
                        <p>Request money from your friend without hesitation.</p>
                        {% if perms.app.add_transaction %}
                            <a href="{% url 'request' %}" class="boxed-btn3-white">Request</a>
                        {% else %}
                            <br>
                        {% endif %}
                    </div>
                </div>
                <div class="col-xl-4 col-md-4">
                    <div class="single_service">
                        <div class="icon">
                            <i class="flaticon-bank"></i>
                        </div>
                        <h3>Transfer</h3>
                        <p>Transfer money to bank with only one click.</p>
                        {% if perms.app.change_account %}
                            <a href="{% url 'account' %}" class="boxed-btn3-white">Transfer</a>
                        {% else %}
                            <br>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- service_area_end -->


    <!-- footer start -->
    <footer class="footer">
        <div class="copy-right_text">
            <div class="container">
                <div class="footer_border"></div>
                    <div class="row">
                        <div class="col-xl-12">
                            <p class="copy_right text-center">
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            </p>
                        </div>
                    </div>
                </div>
            </div>
    </footer>
<!-- footer end  -->

    <!-- link that opens popup -->

    <!-- JS here -->
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js'%}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/ajax-form.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'js/scrollIt.js' %}"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/gijgo.min.js' %}"></script>
    <!--contact js-->
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>

    <script src="{% static 'js/main.js' %}"></script>
    <script>
        $('#datepicker').datepicker({
            iconsLibrary: 'fontawesome',
            icons: {
                rightIcon: '<span class="fa fa-caret-down"></span>'
            }
        });
        $('#datepicker2').datepicker({
            iconsLibrary: 'fontawesome',
            icons: {
                rightIcon: '<span class="fa fa-caret-down"></span>'
            }

        });
    $(document).ready(function() {
    $('.js-example-basic-multiple').select2();
});
    </script>
</body>

</html>